### ISSUE TITLE
This is a duplicated project

### ISSUE THREAD

**Issue by alikhaleghi76** [pouyamaroufi/Persian-Linear-Date-Picker#3]
Hi. 
I think this is a exact copy of my project at [this link](https://github.com/alikhaleghi76/flutter-datepicker). 

Do you have any new feature or specific requirement for duplicating this project?
If you want to implement any new feature, there is no need for publishing it to pub.dev as a separate package. I am asking you to mark the project as discontinued and asking pub.dev support for removal. 

I appreciate it in advance.

**Comment by pouyamaroufi** [comment]
Hi Ali 
At the moment I published this package the project that you mentioned was not updated and had issue with Flutter 3 and null safety. So I have to refactor it. You can compare my initial release with your contribution at 6 month ago. This is a common way in community when a package is not supported by contributors, other developer create another package for others. Like "connectivity" or "better_player" packages.

I didn't know you are fix the issues but I prepared more features to this package like Cupertino Style for Date Picker. Arabic Calendar, Holidays and etc which I will release them at the future. But it doesn't matter to me, if it's bother you I will remove the package but so many developers using it on there project because at the moment flutter 3 was released your package had a issue and so many project was suspended as like mine. I should send you issue and message  but when I saw the package there was unverified uploader and 404 GitHub repository.

**Comment by alikhaleghi76** [comment]
I think it would be more professional to fork from main project, and send PR to fix code or add new changes. 
If the developer announces that the main project is discontinued then you can publish your own version referring main project. 

Any way please fork my project and merge your changes in that, or at least you should add a link to my project in descriptions of project. 

Thank you.
